IKDLEXT ; Обмен данными с внешними лабораториями [ 02/23/2012  9:42 PM ]
DOSEND ; Формирование и отсылка заявок
 N DT,NI,ID,S3,LAB
 S DT=$H-3 F  S DT=$O(^MLABI("d",DT)) Q:DT=""  D
 .S ID="" F  S ID=$O(^MLABI("d",DT,ID)) Q:ID=""  D
 ..S NI=^(ID)
 ..S S3=$P($G(^MLAB(NI,ID,"s3")),"|",1) Q:'S3  
 ..S LAB=$P($G(^("lab")),"|",1) Q:LAB="" 
 ..Q:$P($G(^("s4")),"|",1)=2
 ..Q:$P($G(^("s9")),"|",1)
 ..Q:'$$MKSEND(NI,ID)
 ..D SETSTAT^IMLAB(NI,ID,4,2) ; у контрагента
 Q
MKSEND(NI,ID) 
 Q
