A ;ПОИСК ПАЦИЕНТА  [ 12/25/2006  10:46 AM ]
 Q
IWW ;ПЕРЕКОД. ТАБЛИЦА
 S %DW="" F I=128:1:159,240,160:1:175,224:1:239,241 S %DW=%DW_$C(I)
 S %WD="" F I=192:1:223,168,224:1:239,240:1:255,184 S %WD=%WD_$C(I)
 Q
YF(R,STR) ;ПОИСК ИСТОРИИ
 D YF^YIFIND(R,STR) Q
 ;Q:STR=""
 D:%W IWW
 S:%W STR=$TR(STR,%WD,%DW)
 S DOGG=%LOG,TG=^TG
 S STG=$$DI^DTUTL("0101"_TG),DTK=STG+365
 S PPS=$G(^PP)["LDC"
 D OWF^RWU("buf.nb-data") D POI D C^RWU
 ;S %L="p_find.table.load(buf.txt)",%B="1.nb-proc"
 Q
YFD(STR,DOGG) ;ПОИСК ИСТОРИИ
 ;Q:STR=""
 D:%W IWW
 S:%W STR=$TR(STR,%WD,%DW)
 S TG=^TG
 S STG=$$DI^DTUTL("0101"_TG),DTK=STG+365
 S PPS=$G(^PP)["LDC"
 D OWF^RWU("buf.nb-data") D POI D C^RWU
 Q
POI ;I $G(^PP)["LDC" D POI^YILFIND Q
 S CH=1 I STR?1N.N S N=+STR D WKON Q
 I STR="" D S100 Q
 S OF=STR,SP=5 D SS
 D WKSL
 Q
WKONH D WC^RWU("N И.Б.|Ф.                |И.          |О.         |ОФОР.|СУММА|СРОК    |ДИАГНОЗ MAX СТОИМОСТИ|КОММЕНТАРИЙ"_CR)
 Q
WKON ;I $D(^BT(N,"K")) S L51=^("K") D WW
 I $D(^BT(N)) D WW Q
 E  D WC^RWU("НЕТ ПАЦИЕНТА!"_CR)
 Q
WKSL S N=-1,I=0 F II=1:1 S N=$N(^SL(N)) Q:N=-1  I $D(^BT(N)) D WW
 I I=0 D WC^RWU("НЕТ ПАЦИЕНТА!"_CR)
 Q
S100 S N=0,I=0 F II=1:1 S N=$N(^S(23,TG,DOGG,N)) Q:N=-1  D WW
 Q
WW I CH=1 D WKONH S CH=0
 I 'PPS S R="|",DOG=+$G(^BT(N,27))
 E  S L51=$G(^BT(N,"K")),R="|",DOG=+$E(L51,40,43)
 I DOGG'=9999&(DOGG'="") I DOGG'=DOG Q
 S ND=DOG D CE
 I 'PPS S L52=N_R_$G(^BT(N,2))_R_$G(^(3))_R_$G(^(4))_R_$E($G(^M(52,$G(^(7)))),1,6)_R_DOG_" "_$E($G(^DOG(DOG,2)),1,20)_R_R
 E  S L52=N_R_$P(L51,$C(9),2)_R_$P(L51,$C(9),3)_R_$P(L51,$C(9),4)_R_$E($G(^M(52,$E(L51,7))),1,6)_R_SE_R_$E(L51,50,55)_R_DIA1_R_$P(L51,$C(9),5)
 S I=I+1
 D WC^RWU(L52_CR)
 Q
WWK ;I CH=1 D WKONH S CH=0
 S DOG=+$E(L51,40,43)
 W N,!,$P(L51,$C(9),2),!,$P(L51,$C(9),3),!,$P(L51,$C(9),4),!,$G(^M(52,$E(L51,7))),!,DOG_" "_$E($G(^DOG(DOG,TG,3)),1,20),!,$E(L51,50,55),!,$P(L51,$C(9),5),!
 S POL="М" S:$E(L51,1)=2 POL="Ж" W POL,!
 S RAB="ДА" S:$E(L51,2)=2 RAB="НЕТ" W RAB,!
 W +$E(L51,5,6),!,$E(L51,8,13),!,$E(L51,14,19),!,$E(L51,20,26),!,$E(L51,27,33),!
 W $G(^M(50,+$E(L51,34,35))),!
 W $G(^M(65,+$E(L51,3,4))),!
 W $G(^M(40,+$E(L51,36,39))),!
 W $P(L51,$C(9),6),!,$E(L51,44,49),!
 W $G(^M(70,+$E(L51,56))),!,$G(^M(70,+$E(L51,57))),!,$G(^M(70,+$E(L51,58))),!,$G(^M(70,+$E(L51,59))),!,$G(^M(70,+$E(L51,60))),!,$G(^M(70,+$E(L51,61))),!,$G(^M(70,+$E(L51,62))),!
 Q
SS ;
 ;R "Ф. ",OF
 S R="АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЬЫЪЭЮЯабвгдежзийклмнопрстуфхцчшщьыъэюя|"
 S R1="АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЬЫЪЭЮЯАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЬЫЪЭЮЯ "
 S (FF,OF)=$TR(OF,R,R1)
 S OS="[" S:'$D(SP) SP=5
 S OF=$E($P(OF," ",1),1,6)
 S DF=$L(OF),EF=$E(OF,1,DF-1)_$C($A($E(OF,DF))+1#256)
S3 K ^SL S RR=0,SIK3=0,PIK3=-1 F IK1=1:1 Q:OF<0!(OF="")!(EF']OF)  D B:$D(^S(SP,OF)) S OF=$N(^S(SP,OF))
 K OF,SS,SL Q
 ;
B S IK3=-1 F IK2=1:1 S IK3=$N(^S(SP,OF,IK3)) Q:IK3<0  D PYN I PYN'=0 S ^SL(IK3)="",SIK3=SIK3+1,PIK3=IK3
 Q
PYNSTO S PYN=0 ;ДЛЯ СТОМАТОЛОГИИ
 I $D(^B(IK3)) S AAA=^(IK3),F=$P(AAA,"|",2),F=$TR(F,R,R1),PYN=F I F'[FF S PYN=0 Q
 Q
PYN S PYN=0
 I PPS D  Q
 .I $D(^BT(IK3,"K")) S F=^("K"),F=$P(F,$C(9),2,4),F=$TR(F,$C(9)," "),F=$TR(F,R,R1),PYN=F I F'[FF S PYN=0 Q
 I $D(^BT(IK3)) S F=$G(^BT(IK3,2))_" "_$G(^BT(IK3,3))_" "_$G(^BT(IK3,4)),F=$TR(F,R,R1),PYN=F I F'[FF S PYN=0 Q
 Q
YH(STR,R) ;ПОИСК ИСТОРИИ
 D:%W IWW
 S:%W STR=$TR(STR,%WD,%DW)
 S PPS=$G(^PP)["LDC"
 D OWF^RWU("buf.htm")
 F J=1:1 Q:'$D(^HTML("FIND",J))  D W^RWU(^(J)_CR)
 D POIH
 D W^RWU("</table></div></body></html>"_CR)
 D C^RWU
 Q
POIH ;
 S CH=1 I STR?1N.N S N=+STR D WKONHH Q
 I STR="" D S100H Q
 S OF=STR,SP=5 D SS
 D WKSLH
 Q
WKH D WC^RWU("<tr class=s2><td># ИСТОРИИ</td><td>Ф.</td><td>И.</td><td>О.</td><td>ОФОРМЛЕНИЕ</td><td>ДОГОВОР </td><td>СРОК</td><td>КОММЕНТАРИЙ</td></tr>"_CR)
 Q
WKONHH ;
 I $D(^BT(N)) D WWH Q
 E  D WC^RWU("<tr><td>НЕТ ПАЦИЕНТА!</td></tr>"_CR)
 Q
WKSLH S N=-1 F I=1:1 S N=$N(^SL(N)) Q:N=-1  I $D(^BT(N)) D WWH
 I I=1 D WC^RWU("<tr><td>НЕТ ПАЦИЕНТА!</td></tr>"_CR)
 Q
S100H S N=100 F I=1:1:1000 S N=$N(^BT(N)) Q:N=-1  D WWH
 Q
WWH I CH=1 D WKH S CH=0
 S R="</td><td class=s3>",OTK=0
 I 'PPS S DOG=+$G(^BT(N,27)),L52=$G(^(2))_R_$G(^(3))_R_$G(^(4))_R_$G(^M(52,$G(^(7))))_R_DOG_" "_$E($G(^DOG(DOG,2)),1,20)_R_R,OTK=$G(^(7))
 E  S L51=$G(^BT(N,"K")),OTK=$E(L51,7),DOG=+$E(L51,40,43),L52=$P(L51,$C(9),2)_R_$P(L51,$C(9),3)_R_$P(L51,$C(9),4)_R_$E($G(^M(52,OTK)),1,9)_R_DOG_" "_$E($G(^DOG(DOG,TG,3)),1,20)_R_$E(L51,50,55)_R_$P(L51,$C(9),5)
 S L53="<tr><td class=s1>" S:OTK'=1 L53=L53_"<img src=""/../images/ot.gif"">" S L52=L53_"<a href=""YWH_YIPIKCHL?PR1=%22"_N_"%22""> "_N_"</a></td><td class=s3>"_L52_"</td></tr>"
 D WC^RWU(L52_CR)
 Q
CE S K=1,SE=0,IK3=N K S
 S J1=-1 F J0=1:1 S J1=$N(^BCE(IK3,J1)) Q:J1=-1  D
 .S DT=STG-1 F J2=1:1 S DT=$N(^BCE(IK3,J1,DT)) Q:DT=-1  Q:DT>DTK  D
 ..S NN=-1 F J3=1:1 S NN=$N(^BCE(IK3,J1,DT,NN)) Q:NN=-1  D
 ...S TN=-1 F J4=1:1 S TN=$N(^BCE(IK3,J1,DT,NN,TN)) Q:TN=-1  S DL=-1 F J5=1:1 S DL=$N(^BCE(IK3,J1,DT,NN,TN,DL)) Q:DL=-1  D WCE
 S CC=0,DIA=-1,DIA1="" F  S DIA=$N(S(DIA)) Q:DIA=-1  S:S(DIA)>CC CC=S(DIA),DIA1=DIA
 I DIA1'="" S A=DIA1 D S18 S DIA1=A
 Q
WCE S KL=^(DL),DIA=$P(KL,"/",3)
 ;S AAA=DT D ^MKDT S TGG=$E(BBB,5,6)
 S @("CC=$N(^CE"_TG_"(J1,NN,DT))")
 I CC=-1 S CC=$N(^CE(J1,NN,DT))
 I ND=1!(ND=76)!(ND=16)!(ND=28)!(ND=48)!(ND=47)!(ND=54)!(ND=99) D ^XWUD G SCECU
 I CC=-1 S CC=0
 E  S CC=^(CC)
SCECU S CC=CC*KL,SE=SE+CC
 S:DIA'="" S(DIA)=$G(S(DIA))+CC
 Q
A18 S A=$E("0000",1,5-$L(A))_A
 S L7=+$E(A,1,3),L8=+$E(A,4,5),L9=$D(^D9(L7,"z",L8)),L6=$D(^D9(L7,"r"))
 S:L6=0&(L9=0) A="дг:"_A_" нет!" S:L9'=0 A=$P(^D9(L7,"z",L8),"/",2) S:L9=0&(L6'=0) A=$P(^D9(L7,"r"),"/",2)
 Q
S18 ;
 S A=$TR(A,".""","")
 S:$E(A,1)="0" A=$E(A,2,250)
 S:$E(A,1)="0" A=$E(A,2,250)
 I $E(A,1)?1N G A18
 I A="" Q
 S L7=$E(A,1,3),L8=$E(A,4) S:L8="" L8="Z" S L9=$D(^D(L7,"z",L8)),L6=$D(^D(L7,"r")) S:L6=0&(L9=0) A="дг:"_A_" нет !" S:L9'=0 A=$P(^D(L7,"z",L8),"/",2) S:L9=0&(L6'=0) A=$P(^D(L7,"r"),"/",2)
 Q
