A ;ПОИСК ПАЦИЕНТА  [ 01/16/2007  10:22 AM ]
 Q
IWW ;ПЕРЕКОД. ТАБЛИЦА
 S %DW="" F I=128:1:159,240,160:1:175,224:1:239,241 S %DW=%DW_$C(I)
 S %WD="" F I=192:1:223,168,224:1:239,240:1:255,184 S %WD=%WD_$C(I)
 Q
YF(R,STR) ;ПОИСК ИСТОРИИ
 ;Q:STR=""
 D:%W IWW
 S NI=+STR,OF(1)="Прикр.",OF(2)="Снят",OF(3)="Почил" S:%W STR=$TR(STR,%WD,%DW)
 D OWF^RWU("1.txt"),WC^RWU("N И.Б.|Фамилия|Имя|Отчество|Оформ.|Договор|Срок")
 I STR=NI S NIB=NI D YFPC G YFCLS
 S LLU="АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯЁ",LLL="абвгдежзийклмнопрстуфхцчшщъыьэюяё",STR=$TR(STR,LLU,LLL)
 S NIB=-1 F   S NIB=$N(^BTN(NIB)) Q:NIB=-1  S FIO=$G(^BTN(NIB,"fiof")),FIO=$TR(FIO,LLU,LLL) D:FIO[STR YFPC
 K LLU,LLL
YFCLS D C^RWU
 ;S %L="p_find.table.load(buf.txt)",%B="1.nb-proc"
 Q
YFPC S DN=$G(^BTN(NIB,"stc")),A=NIB_"|"_$G(^BTN(NIB,"fiof"))_"|"_$G(^("fioi"))_"|"_$G(^("fioo"))_"|"_$G(OF($G(^BTN(NIB,"ofor"))))_"|"_$G(^DOG(DN,"06",3))_"|"_$G(^BTN(NIB,"dofor"))
 D WC^RWU(CR_A)
 Q
YFD(STR,DOGG) ;ПОИСК ИСТОРИИ ПО ДОГОВОРУ
 D YFD^YIFINDN(STR,DOGG)
 Q
 ;Q:STR=""
 S MRR=""
 D:%W IWW
 S:%W STR=$TR(STR,%WD,%DW)
 S TG=^TG
 S STG=$$DI^DTUTL("0101"_TG),DTK=STG+365
 S FN="buf.nb-data"
 D OW^RWU D POI D C^RWU
 S %B=FN
 Q
YFM(STR,MRR) ;ПОИСК ИСТОРИИ ПО МЕСТУ РАБОТЫ
 ;Q:STR=""
 S DOGG="" S:MRR=0 MRR=""
 D:%W IWW
 S:%W STR=$TR(STR,%WD,%DW)
 S TG=^TG
 S STG=$$DI^DTUTL("0101"_TG),DTK=STG+365
 S FN="buf.nb-data"
 D OW^RWU D POI D C^RWU
 S %B=FN
 Q
YFPL(STR,DOGG) ;ПОИСК ИСТОРИИ ПО ПОЛИСУ  
 S MRR=""
 D:%W IWW
 S:%W STR=$TR(STR,%WD,%DW)
 S TG=^TG
 S STG=$$DI^DTUTL("0101"_TG),DTK=STG+365
 S FN="buf.nb-data"
 D OW^RWU D POIP D C^RWU
 S %B=FN
 Q
POI ;
 S CH=1 I STR?1N.N S N=+STR D WKON Q
 I STR="" D S100 Q
 S OF=STR,SP=5 D SS
 D WKSL
 Q
POIP ;
 S CH=1
 I STR="" D S100 Q
 S OF=STR,SP=18 D SSP
 D WKSL
 Q
WKONH D WC^RWU("N И.Б.|Ф.                |И.          |О.         |ОФОР.|СУММА|СРОК    |ДИАГНОЗ MAX СТОИМОСТИ|КОММЕНТАРИЙ"_CR)
 Q
WKON ;
 I $D(^BT(N)) D WW Q
 E  D WC^RWU("НЕТ ПАЦИЕНТА!"_CR)
 Q
WKSL S N=-1,I=0 F II=1:1 S N=$N(^SL(N)) Q:N=-1  I $D(^BT(N)) D WW
 I I=0 D WC^RWU("НЕТ ПАЦИЕНТА!"_CR)
 Q
S100 S N=0,I=0 F II=1:1 S N=$N(^S(2,DOGG,N)) Q:N=-1  D WW
 Q
WW I CH=1 D WKONH S CH=0
 S L51=$G(^BT(N,"K")),R="|",DOG=+$E(L51,40,43)
 I DOGG'=9999&(DOGG'="") I DOGG'=DOG Q
 I MRR'="" S MR=+$E(L51,36,39) Q:MR'=MRR
 S ND=DOG D CE
 S L52=N_R_$P(L51,$C(9),2)_R_$P(L51,$C(9),3)_R_$P(L51,$C(9),4)_R_$E($G(^M(52,$E(L51,7))),1,6)_R_SE_R_$E(L51,50,55)_R_DIA1_R_$P(L51,$C(9),5)
 S I=I+1
 D WC^RWU(L52_CR)
 Q
SS ;
 ;R "Ф. ",OF
 S R="АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЬЫЪЭЮЯабвгдежзийклмнопрстуфхцчшщьыъэюя|"
 S R1="АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЬЫЪЭЮЯАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЬЫЪЭЮЯ "
 S (FF,OF)=$TR(OF,R,R1)
 S OS="[" S:'$D(SP) SP=5
 S OF=$E($P(OF," ",1),1,6)
 S DF=$L(OF),EF=$E(OF,1,DF-1)_$C($A($E(OF,DF))+1#256)
S3 K ^SL S RR=0,SIK3=0,PIK3=-1 F IK1=1:1 Q:OF<0!(OF="")!(EF']OF)  D B:$D(^S(SP,OF)) S OF=$N(^S(SP,OF))
 K OF,SS,SL Q
 ;
B S IK3=-1 F IK2=1:1 S IK3=$N(^S(SP,OF,IK3)) Q:IK3<0  D PYN I PYN'=0 S ^SL(IK3)="",SIK3=SIK3+1,PIK3=IK3
 Q
PYN S PYN=0
 I $D(^BT(IK3,"K")) S F=^("K"),F=$P(F,$C(9),2,4),F=$TR(F,$C(9)," "),F=$TR(F,R,R1),PYN=F I F'[FF S PYN=0 Q
 Q
SSP ;
 S (FF,OF)=OF
 S OS="=" I OF["*" S (FF,OF)=$P(OF,"*",1),OS="[" S EF=$E(OF_"zzzzzz",1,16),OF=$E(OF_"      ",1,16)
 E  S DF=$L(OF),EF=$E(OF,1,DF-1)_$C($A($E(OF,DF))+1#256)
 K ^SL S RR=0,SIK3=0,PIK3=-1 F IK1=1:1 Q:OF<0!(OF="")!(EF']OF)  D BP:$D(^S(SP,OF)) S OF=$N(^S(SP,OF))
 K OF,SS,SL Q
 ;
BP S IK3=-1 F IK2=1:1 S IK3=$N(^S(SP,OF,IK3)) Q:IK3<0  D PYNP I PYN'=0 S ^SL(IK3)="",SIK3=SIK3+1,PIK3=IK3
 Q
PYNP S PYN=1
 I $D(^BT(IK3,"K")) S F=^("K"),L6=$P(F,$C(9),6) I @("L6'"_OS_"FF") S PYN=0
 Q
CE S K=1,SE=0,IK3=N K S
 S J1=-1 F J0=1:1 S J1=$N(^BCE(IK3,J1)) Q:J1=-1  D
 .S DT=STG-1 F J2=1:1 S DT=$N(^BCE(IK3,J1,DT)) Q:DT=-1  Q:DT>DTK  D
 ..S NN=-1 F J3=1:1 S NN=$N(^BCE(IK3,J1,DT,NN)) Q:NN=-1  D
 ...S TN=-1 F J4=1:1 S TN=$N(^BCE(IK3,J1,DT,NN,TN)) Q:TN=-1  S DL=-1 F J5=1:1 S DL=$N(^BCE(IK3,J1,DT,NN,TN,DL)) Q:DL=-1  D WCE
 S CC=0,DIA=-1,DIA1="" F  S DIA=$N(S(DIA)) Q:DIA=-1  S:S(DIA)>CC CC=S(DIA),DIA1=DIA
 I DIA1'="" S A=DIA1 D S18 S DIA1=A
 Q
WCE S KL=^(DL),DIA=$P(KL,"/",3)
 ;S AAA=DT D ^MKDT S TGG=$E(BBB,5,6)
 S @("CC=$N(^CE"_TG_"(J1,NN,DT))")
 I CC=-1 S CC=$N(^CE(J1,NN,DT))
 I ND=1!(ND=76)!(ND=16)!(ND=28)!(ND=48)!(ND=47)!(ND=54)!(ND=99) D ^XWUD G SCECU
 I CC=-1 S CC=0
 E  S CC=^(CC)
SCECU S CC=CC*KL,SE=SE+CC
 S:DIA'="" S(DIA)=$G(S(DIA))+CC
 Q
A18 S A=$E("0000",1,5-$L(A))_A
 S L7=+$E(A,1,3),L8=+$E(A,4,5),L9=$D(^D9(L7,"z",L8)),L6=$D(^D9(L7,"r"))
 S:L6=0&(L9=0) A="дг:"_A_" нет!" S:L9'=0 A=$P(^D9(L7,"z",L8),"/",2) S:L9=0&(L6'=0) A=$P(^D9(L7,"r"),"/",2)
 Q
S18 ;
 S A=$TR(A,".""","")
 S:$E(A,1)="0" A=$E(A,2,250)
 S:$E(A,1)="0" A=$E(A,2,250)
 I $E(A,1)?1N G A18
 I A="" Q
 S L7=$E(A,1,3),L8=$E(A,4) S:L8="" L8="Z" S L9=$D(^D(L7,"z",L8)),L6=$D(^D(L7,"r")) S:L6=0&(L9=0) A="дг:"_A_" нет !" S:L9'=0 A=$P(^D(L7,"z",L8),"/",2) S:L9=0&(L6'=0) A=$P(^D(L7,"r"),"/",2)
 Q
